/* INNER JOIN */

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM ALUMNO A INNER JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,SEXO,D.NOMBRE FROM ALUMNO A INNER JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO WHERE SEXO='M'

SELECT APE_APAT,APE_AMAT,P.NOMBRE,SEXO,D.NOMBRE AS [NOMBRE DISTRITO] FROM PROFESORES P INNER JOIN DISTRITO D ON P.COD_DIST=D.COD_DISTRITO

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,APE_APAT,APE_AMAT,P.NOMBRE,FECHA FROM ALUMNO A INNER JOIN DETALLE_FALTA DF ON A.COD_ALUMNO=DF.COD_ALUMNO INNER JOIN PROFESORES P ON P.COD_PROFESOR=DF.COD_PROF

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,APE_APAT,APE_AMAT,P.NOMBRE,FECHA, DESCRIPCION FROM ALUMNO A INNER JOIN DETALLE_FALTA DF ON A.COD_ALUMNO=DF.COD_ALUMNO INNER JOIN PROFESORES P ON P.COD_PROFESOR=DF.COD_PROF INNER JOIN FALTAS F ON F.COD_FALTA=DF.COD_FALTA


SELECT A.NOMBRE,APAT_PAT,APAT_MAT,APE_APAT,APE_AMAT,P.NOMBRE,FECHA, F.DESCRIPCION AS [DESCRIPCION FALTA], S.DESCRIPCION AS [DESCRIPCION SANCION] FROM ALUMNO A INNER JOIN DETALLE_FALTA DF ON A.COD_ALUMNO=DF.COD_ALUMNO INNER JOIN PROFESORES P ON P.COD_PROFESOR=DF.COD_PROF INNER JOIN FALTAS F ON F.COD_FALTA=DF.COD_FALTA INNER JOIN SANCIONES S ON S.COD_SANCION=DF.COD_SANCION



/*LEFT JOIN */
SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM ALUMNO A INNER JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM ALUMNO A LEFT JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM DISTRITO D LEFT JOIN ALUMNO A ON A.COD_DIST=D.COD_DISTRITO


/* FULL JOIN */

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM ALUMNO A FULL JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO


/* RIGHT JOIN*/
SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM ALUMNO A RIGHT JOIN DISTRITO D ON A.COD_DIST=D.COD_DISTRITO

SELECT A.NOMBRE,APAT_PAT,APAT_MAT,D.NOMBRE FROM DISTRITO D RIGHT JOIN ALUMNO A ON A.COD_DIST=D.COD_DISTRITO