/*CREAR UNA BASE DE DATOS*/

CREATE DATABASE INFORMATICA

USE INFORMATICA

/*CREAR UNA TABLA CLIENTE*/

CREATE TABLE CLIENTE
(COD_CLIENTE		CHAR(5) NOT NULL PRIMARY KEY,
APAT				VARCHAR(30)	NOT NULL,
AMAT				VARCHAR(30)	NOT NULL,
NOMBRE				VARCHAR(30)		NOT NULL,
FECHA_NAC			DATE		NOT NULL,
SEXO				CHAR(1)		NOT NULL,
SUBCIDIO			DECIMAL(10,2)	NOT NULL)

/* INSERCION DE REGISTROS (INSERT INTO)*/

/* FORMA 1*/

INSERT INTO CLIENTE(COD_CLIENTE,APAT,AMAT,NOMBRE,FECHA_NAC,SEXO,SUBCIDIO) VALUES ('C0001','QUIROZ','FERNADEZ','FLOR MARIA','12/12/1998','F',1800)

SELECT * FROM CLIENTE
INSERT INTO CLIENTE(COD_CLIENTE,APAT,AMAT,NOMBRE,FECHA_NAC,SEXO,SUBCIDIO) VALUES ('C0002','AGUILAR','SOTO','JUAN JOSE','12/12/1999','M',2000)

/*FORMA 2*/

INSERT INTO CLIENTE VALUES ('C0003','HERNANDEZ','ALEJO','JOSEFINA','12/12/1997','F',1500),
							('C0004','DURAN','MENDOZA','MANUEL','12/12/1996','M',1900),
							('C0005','VENTURA','CACERES','JAVIER','12/12/1999','M',1300),
							('C0006','CACIRE','GOMEZ','MARTHA','12/12/1997','F',2100)

INSERT INTO CLIENTE VALUES ('C0007','BRAVO','ALEJO','FLOR','12/12/1997','F',1500)
/* ACTUALIZAR DATOS DENTRO LA TABLA (UPDATE)*/

UPDATE CLIENTE SET AMAT='SOLORZANO',NOMBRE='JUAN CARLOS' WHERE COD_CLIENTE='C0002'

SELECT * FROM CLIENTE

UPDATE CLIENTE SET APAT='CACCIRE',FECHA_NAC='12-12-2007' WHERE COD_CLIENTE='C0006'

UPDATE CLIENTE SET SUBCIDIO=SUBCIDIO+50 WHERE SEXO='F'

UPDATE CLIENTE SET SUBCIDIO=SUBCIDIO + (SUBCIDIO*0.1) WHERE SEXO='M'

UPDATE CLIENTE SET SUBCIDIO=SUBCIDIO + 100  WHERE YEAR(FECHA_NAC)=1999

UPDATE CLIENTE SET NOMBRE='JORGE'

/* ELIMAR REGISTRO (DELETE) */

DELETE FROM CLIENTE 

DELETE FROM CLIENTE WHERE SEXO='F' 

SELECT * FROM CLIENTE

DELETE FROM CLIENTE WHERE SUBCIDIO>=1300 AND SUBCIDIO<=1900

DELETE FROM CLIENTE WHERE COD_CLIENTE='C0002'


DELETE FROM CLIENTE WHERE SUBCIDIO BETWEEN 1300 AND 1900

DELETE FROM CLIENTE WHERE SEXO IN('M')

DELETE FROM CLIENTE WHERE SEXO IN('F')

DELETE FROM CLIENTE WHERE COD_CLIENTE IN('C0001','C0004','C0006')

DELETE FROM CLIENTE WHERE COD_CLIENTE='C0002' OR COD_CLIENTE='C0003' OR COD_CLIENTE='C0005'

/*CONSULTA DE REGISTROS (SELECT) */


SELECT * FROM CLIENTE

SELECT * FROM CLIENTE WHERE SEXO='M'

SELECT * FROM CLIENTE WHERE SUBCIDIO>=1900


SELECT * FROM CLIENTE WHERE SUBCIDIO>=1900 AND SEXO='F'

SELECT * FROM CLIENTE ORDER BY APAT


SELECT * FROM CLIENTE ORDER BY SUBCIDIO 

SELECT * FROM CLIENTE ORDER BY SUBCIDIO  DESC

/* UTILIZACION DEL LIKE*/

SELECT * FROM CLIENTE WHERE APAT LIKE 'A%'

SELECT * FROM CLIENTE WHERE APAT LIKE '%A%'

SELECT * FROM CLIENTE WHERE APAT LIKE '%Z'

SELECT * FROM CLIENTE WHERE APAT LIKE '_U%'

SELECT * FROM CLIENTE WHERE APAT LIKE '[A,C,D]%'

SELECT * FROM CLIENTE WHERE APAT LIKE '[A-D]%'

/*-------------------------------------*/

SELECT * FROM CLIENTE WHERE NOT SEXO='M'


SELECT * FROM CLIENTE WHERE SUBCIDIO BETWEEN 1300 AND 1900








