CREATE DATABASE SISTEMA



/* CREAR UNA TABLA */

CREATE TABLE CLIENTE
(COD_CLIENTE	CHAR(5)		NOT NULL,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
FECHA_NAC		DATE		NOT NULL,
TELEF_FIJO		CHAR(11)	NULL
)

/* MODIFICAR CARACTERISTICA DE UN CAMPO*/

ALTER TABLE CLIENTE
ALTER COLUMN APE_PAT	VARCHAR(50) NOT NULL


ALTER TABLE CLIENTE
ALTER COLUMN APE_MAT	VARCHAR(50) NOT NULL

/*ADIOCIONAR UN CAMPO*/
ALTER TABLE CLIENTE
ADD EMAIL VARCHAR(60)

ALTER TABLE CLIENTE
ADD EDAD INT NOT NULL

/*ELIMINAR UN CAMPO */
ALTER TABLE CLIENTE
DROP COLUMN EDAD

/* ELIMINAR UNA TABLA */
DROP TABLE CLIENTE


/*ESTABLECER UNA LLAVE PRIMARIA */

/*PRIMERA FORMA LLAVE PRIMARIA*/

CREATE TABLE CLIENTE
(COD_CLIENTE	CHAR(5)		NOT NULL	PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
)

/*SEGUNDA FORMA LLAVE PRIMARIA*/
CREATE TABLE CLIENTE1
(COD_CLIENTE	CHAR(5)		NOT NULL,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
CONSTRAINT PK_CLIENTE1 PRIMARY KEY (COD_CLIENTE)
)

/*TERCERA FORMA LLAVE PRIMARIA */
CREATE TABLE CLIENTE2
(COD_CLIENTE	CHAR(5)		NOT NULL,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL
)

ALTER TABLE CLIENTE2
ADD CONSTRAINT PK_CLIENTE2 PRIMARY KEY(COD_CLIENTE) 

/*LLAVE SECUNDARUIA / FOREIGN KEY */
/*PRIMERA FORMA */

CREATE TABLE DISTRITO
(COD_DISTRITO	CHAR(6) NOT NULL PRIMARY KEY,
NOMBRE			VARCHAR(50)	NOT NULL)


CREATE TABLE CLIENTE3
(COD_CLIENTE	CHAR(5)		NOT NULL PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
COD_DIST		CHAR(6)		NOT NULL,
CONSTRAINT FK_CLIENTE3_DISTRITO FOREIGN KEY (COD_DIST) REFERENCES DISTRITO(COD_DISTRITO)
)

/*SEGUNDA FORMA*/
CREATE TABLE CLIENTE4
(COD_CLIENTE	CHAR(5)		NOT NULL PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
COD_DIST		CHAR(6)		NOT NULL
)

ALTER TABLE CLIENTE4
ADD CONSTRAINT FK_CLIENTE4_DISTRITO FOREIGN KEY (COD_DIST) REFERENCES DISTRITO(COD_DISTRITO)

/*RESTRICCIONES A COLUMNAS*/
/* UTILIZACION DEL IDENTITY */

CREATE TABLE ALUMNOS 
(COD_ALUMN INT NOT NULL IDENTITY(1,1),
PAT	VARCHAR(50) NOT NULL,
MAT	VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL)

/* DEFAULT */
CREATE TABLE CLIENTE5
(COD_CLIENTE	CHAR(5)		NOT NULL PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
EMAIL			VARCHAR(50) NOT NULL DEFAULT 'SIN CORREO ELECTRONICO',
TELEFONO_FIJO	CHAR(11)	NULL
)


ALTER TABLE CLIENTE5
ADD DEFAULT 'SIN TELEFONO' FOR TELEFONO_FIJO


/*CHECK */
CREATE TABLE CLIENTE6
(COD_CLIENTE	CHAR(5)		NOT NULL PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL,
EMAIL			VARCHAR(50) NOT NULL DEFAULT 'SIN CORREO ELECTRONICO',
SEXO			CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
EDAD			INT		NOT NULL	CHECK(EDAD BETWEEN 18 AND 80)
)

ALTER TABLE CLIENTE6
ADD CATEGORIA	CHAR(1)

ALTER TABLE CLIENTE6
ADD CHECK (CATEGORIA IN('A','B','C','D'))


/*UNIQUE */

/*CHECK */
CREATE TABLE CLIENTE7
(COD_CLIENTE	CHAR(5)		NOT NULL PRIMARY KEY,
APE_PAT			VARCHAR(30)	NOT NULL,
APE_MAT			VARCHAR(30)	NOT NULL,
NOMBRE			VARCHAR(30)	NOT NULL,
DNI				CHAR(8)		NOT NULL UNIQUE,
EMAIL			VARCHAR(50) NOT NULL DEFAULT 'SIN CORREO ELECTRONICO',
SEXO			CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
EDAD			INT		NOT NULL	CHECK(EDAD BETWEEN 18 AND 80)
)


ALTER TABLE CLIENTE7
ADD TELEFONO CHAR(9) NOT NULL


ALTER TABLE CLIENTE7
ADD CONSTRAINT UNI_TELEFONO UNIQUE (TELEFONO)
