 /* CREATE TABLE */
CREATE TABLE IF NOT EXISTS TABLE_NAME(
TRETRETRETRETRETRETRETRET VARCHAR( 100 )
);

/* INSERT QUERY */
INSERT INTO TABLE_NAME( TRETRETRETRETRETRETRETRET )
VALUES
(
    'RETRETRETRETERT'
);
